ofcourse/ofcourse/urls.py
from django.contrib import admin
from django.urls import path, include
from course import views
from course.views import index


urlpatterns = [
    path('', index, name='index'),

    path('admin/', admin.site.urls),

    # path('list/', list),
    path('course/', views.course, name='course'),

    # company
    path('company/', include('company.urls')),

    # stack
    path('stack/', include('stack.urls')),

    # search 
    path('search/', views.search, name='search'),

    # filter 
    path('filter/', views.filter, name='filter'),
]

ofcourse/stack/urls.py
from stack import views
from django.urls import path

app_name = 'stack'

urlpatterns = [
    # '/stack/
    path('', views.StackList.as_view(), name="stack"),

    # stack_detail
    path('<int:pk>/',views.StackDetail.as_view(), name='stack_detail'),

    # stack_search
    path('search/', views.search, name='search'),
]

ofcourse/course/models.py
from django.db import models

# Create your models here.

# 강의 모델
class Course(models.Model):
    url = models.TextField(default=None)
    img_url = models.TextField( default=None)
    title = models.CharField(max_length=200,default=None)
    teacher = models.CharField(max_length=200,default='')
    headline = models.TextField(default='')
    level = models.CharField(max_length=30,default='')
    score = models.FloatField(default=0, null=True)
    course_time = models.CharField(max_length=100,default='')
    student_cnt = models.IntegerField(default=0, null=True)
    recommend = models.IntegerField(default=0,null=True)
    review_cnt = models.IntegerField(default=0,null=True)
    price = models.IntegerField(default='',null=True)
    rank = models.FloatField(default=None, null=True)
    stack = models.ManyToManyField("Stack",through='Course_Stack')
    sentiment = models.FloatField(default=0, null=True)

    class Meta:
        db_table='Course'

# 스택테이블
class Stack(models.Model):  
    name = models.CharField(max_length=50,unique=True)
    logo = models.TextField(default='')
    assort = models.CharField(max_length=50,default='')
    described = models.TextField()

    class Meta:
        db_table ='Stack'

# Course_Stack 중간테이블
class Course_Stack(models.Model):
    course =models.ForeignKey('Course',on_delete=models.CASCADE)
    stack =models.ForeignKey('Stack',on_delete=models.CASCADE)

    class Meta:
        db_table='Course_Stack'

# 회사테이블
class Company(models.Model):
    name = models.CharField(max_length=50,unique=True)
    logo = models.TextField(default='')
    stack_info = models.CharField(max_length=200,default='')
    stack = models.ManyToManyField("Stack",through='Company_Stack')
    category = models.CharField(max_length=50,null=True)
    company_link = models.TextField(default='')
    company_recruit_link = models.TextField(default='')

    class Meta:
        db_table = 'Company'

#Company_Stack 중간테이블
class Company_Stack(models.Model):
    company =models.ForeignKey('Company',on_delete=models.CASCADE)
    stack =models.ForeignKey('Stack',on_delete=models.CASCADE)

    class Meta:
        db_table = 'Company_Stack'


#related_stack 테이블
class Related_Stack(models.Model):
    stack_name= models.ForeignKey('Stack',on_delete=models.CASCADE)
    related_stack = models.CharField(max_length=50)
    related_stack_logo = models.TextField(default='')
    related_stack_pk = models.IntegerField(default=0)

    class Meta:
        db_table = 'Related_Stack'

#stack_dict 테이블 입니다.
class Stack_Dict(models.Model):
    stack_name= models.ForeignKey('Stack',on_delete=models.CASCADE)
    search_word= models.CharField(max_length=20)

    class Meta:
        db_table = 'Stack_Dict'

ofcourse/stack/models.py
from django.db import models
from django.shortcuts import render
# Create your models here.

ofcourse/stack/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from course.models import Stack, Related_Stack, Company, Course_Stack
from django.shortcuts import get_object_or_404
from django.db.models import Q

# Create your views here.
class StackList(ListView): 
    model = Stack
    template_name = "stack/stack_list.html"
    ordering = '?'
    paginate_by = 12

    def get_context_data(self, **kwargs):
        context = super(StackList, self).get_context_data()
        context['stack'] = Stack.objects.all()

        filter = self.request.GET.get('filter','') #url의 쿼리스트링을 가져온다. 없는 경우 공백을 리턴한다

        if filter == 'frontend':
            context['object_list'] = Stack.objects.filter(assort__iexact = '프론트엔드')
            context['page'] = 'filter'
        elif filter == 'backend':
            context['object_list'] = Stack.objects.filter(assort__iexact = '백엔드')
            context['page'] = 'filter'
        elif filter == 'database':
            context['object_list'] = Stack.objects.filter(assort__iexact = '데이터베이스')
            context['page'] = 'filter'
        elif filter == 'DevOps':
            context['object_list'] = Stack.objects.filter(assort__iexact = '데브옵스')
            context['page'] = 'filter'
        elif filter == 'Language':
            context['object_list'] = Stack.objects.filter(assort__iexact = '언어')
            context['page'] = 'filter'
        elif filter == 'data':
            context['object_list'] = Stack.objects.filter(assort__iexact = '데이터')
            context['page'] = 'filter'
        elif filter == 'TestingTool':
            context['object_list'] = Stack.objects.filter(assort__iexact = '테스팅툴')
            context['page'] = 'filter'
        elif filter == 'businessTool':
            context['object_list'] = Stack.objects.filter(assort__iexact = '협업툴')
            context['page'] = 'filter'
        elif filter == 'mobile':
            context['object_list'] = Stack.objects.filter(assort__iexact = '모바일')
            context['page'] = 'filter'

        return context


class StackDetail(DetailView):
    model = Stack
    template_name = 'stack/stack_detail.html'

    def get_context_data(self, **kwargs):
        context = super(StackDetail, self).get_context_data()
        try:
            context['course'] = Course_Stack.objects.filter(stack_id=self.object.id).order_by('course__rank')[:5]
        except Exception as e:
            context['course'] = None

        return context

def search(request):
    stacks = Stack.objects.all()
    search = request.GET.get('search','')
    if search:
        stack_list = stacks.filter(
            Q(name__icontains=search) |
            Q(stack_dict__search_word__iexact=search)
        ).distinct()
        return render(request, 'stack/stack_search.html', {'stack':stack_list, 'search':search})
    else:
        return render(request,  'stack/stack_search.html')

    # def get_context_data(self, **kwargs):
    #     context = super(StackDetail, self).get_context_data()
    #     st =Stack.objects.filter(id=2).prefetch_related('company_set')[0]
    #     print(st)
    #     context['companies'] = st.course_set.all()
    #     print(context['companies'])
    #     for i in context['companies']:
    #         print("cours :", i)

        # context = super(StackDetail, self).get_context_data()
        # st =Stack.objects.filter(id=2).prefetch_related('course_set')[0]
        # print(st)
        # context['courses'] = st.course_set.all()
        # print(context['courses'])
        # for i in context['courses']:
        #     print("cours :", i)
        
        # context['companies'] = Stack.objects.filter(id=1).prefetch_related('company_set')
        # return context

    # def get_context_data(self, **kwargs):
    #     context = super(StackDetail, self).get_context_data()
    #     context['test'] = Company.objects.all()
    #     return context

ofcourse/stack/templates/stack/stack_detail.html
{% load static %}
{% load humanize %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ofcourse</title>
    <!-- fontawesome css cdn-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
        integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- normalize css cdn-->
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <!-- global css -->
    <link rel="stylesheet" href="{%static 'css/style.css'%}">
</head>

<body class="list-page">
    <header>
        {% include 'partials/navbar.html' %}
    </header>
    <div class="view content col-2">
        <aside>
            <div class="skill-info-area">
                <div class="skill-icon">
                    <!-- 스택 이름, 로고 -->
                    <img src="{{ stack.logo }}" alt="skill icon">
                </div>
                <h3>{{ stack.name }}</h3>
                <br>
                <p class="skill-category">{{stack.assort}}</p>
                <p class="skill-info">{{ stack.described}}</p>
            </div>
        </aside>
        <!-- 강의 목록 -->
        <main class="view-area list-area">
            <div class="info-box">
                <h3 class="skill-title"> 연관 강의 BEST5 </h3>
                <ul class="course-list">
                    {% for cor in course %}
                    <li class="list-card">
                        <div class="img-box">
                            <a href="{{cor.course.url}}" target="_blank">
                                <img src="{{cor.course.img_url}}" alt="강의 예시 이미지">
                            </a>
                        </div>
                        <div class="info-box">
                            <h3><a href="{{cor.course.url}}">{{cor.course.title}}</a></h3>
                            <p class="teacher">{{cor.course.teacher}}</p>
                            <p class="rate">{{cor.course.score}}</p>
                            {% if cor.course.price == null %}
                            <p class="price">🔗</p>
                            {% elif cor.course.price == 0 %}
                            <p class="price">무료</p>
                            {% else %}
                            <p class="price">{{ cor.course.price|intcomma }}</p>
                            {% endif %}
                        </div>
                    </li>
                    {% endfor %}
                </ul>
                <!-- 기업 목록 -->
            </div>
            <div class="info-box">
                <h3 class="skill-title">사용중인 기업</h3>
                <ul class="skill-list">
                    {% for com in stack.company_set.iterator %}
                    <li>
                        <a href="/company/{{com.id}}">
                            <i class="skill-icon"><img src="{{ com.logo }}" alt="스킬 아이콘"></i>
                            <p class="skill-name">{{ com.name }}</p>
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </main>
    </div>
    <footer>
        <p>
            Copyright © 2023. Kokonenne All Rights Reserved.
        </p>
    </footer>
</body>

</html>

ofcourse/stack/templates/stack/stack_list.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ofcourse</title>
    <!-- fontawesome css cdn-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
        integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- normalize css cdn-->
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <!-- global css -->
    <link rel="stylesheet" href="{%static 'css/style.css'%}">
</head>

<body class="list-page">
    <header>
        {% include 'partials/navbar.html' %}
    </header>
    <div class="title-area">
        <h2 class="page-title">기술 스택별 정보</h2>
        <p class="detail-title">기술 스택을 사용하는 기업 정보와 연관 강의를 추천 받아보세요!👍</p>
    </div>

    <div class="search-area">
        <form action="{% url 'stack:search' %}" method="GET">
            {% csrf_token %}
            <div class="search-bar">
                <input type="text" name="search" id="search-bar" placeholder="스택명을 입력해주세요 !">
                <button type="submit" class="search-btn">검색</button>
            </div>
        </form>
    </div>


    <div class="content">
        <div class="filter-area">
            <div class="btn-wrap">
                <div class="btn-r-wrap">
                    <p class="title">필터 </p>
                    <a class="btn" href="/stack">All</a>
                    <a class="btn" href="?filter=Language">언어</a>
                    <a class="btn" href="?filter=frontend">프론트엔드</a>
                    <a class="btn" href="?filter=backend">백엔드</a>
                    <a class="btn" href="?filter=database">데이터베이스</a>
                    <a class="btn" href="?filter=DevOps">데브옵스</a>
                    <a class="btn" href="?filter=data">데이터</a>
                    <a class="btn" href="?filter=mobile">모바일</a>
                    <a class="btn" href="?filter=TestingTool">테스팅툴</a>
                    <a class="btn" href="?filter=businessTool">협업툴</a>
                </div>
            </div>
        </div>
        <main class="list-area skill">
            <ul>
                {% for s in object_list %}
                <li class="list-card">
                    <div class="company-icon">
                        <a href="{{s.id}}">
                            <img src="{{ s.logo }}" alt="스택 로고">
                        </a>
                    </div>
                    <div class="info-box">
                        <a href="{{s.id}}" style="text-decoration: none;">
                            <h3>{{ s.name }}  <span class="sort">{{s.assort}}</span></h3>
                        </a>
                    </div>
                    <p class="skill-info">
                        연관 기술 스택
                    </p>
                    <div class="skill-list">
                        <ul>
                            {% for rs in s.related_stack_set.iterator %}
                            <li>
                                <a class="skill-icon" href="{{rs.related_stack_pk}}">
                                    <img src="{{ rs.related_stack_logo }}" alt="아이콘">
                                </a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </main>
    </div>
    {% if page != 'filter' %}
    <ul class="pagination">

        <!-- 이전 페이지 객체가 있으면 '이전' 버튼 활성화 -->
        {% if page_obj.has_previous %}
        <a class="btn" href="/stack/?page={{ page_obj.previous_page_number }}" tabindex="-1"><i
                class="fa-solid fa-angle-left"></i></a>
        {% else %}
        <!-- <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">이전</a>
            </li> -->
        <a class="btn disabled" tabindex="-1"><i class="fa-solid fa-angle-left"></i></a>
        {% endif %}


        {# 페이지를 번호로 출력하기 #}
        {% for page in page_obj.paginator.page_range %} {# 전체 페이지수를 가져옴 #}
        {# 현재 선택한 페이지 번호는 비활성화 시킴 #}
        {% if page_obj.number == forloop.counter %}
        {# 위에 page_obj 대신 page 로도 되는지 테스트해보기 #}
        <li>
            {# 현재 선택한 페이지 번호는 활성화 시킴 #}
            <a class="btn on" href="{{ request.path }}?page={{ forloop.counter }}">{{ forloop.counter }}</a>
        </li>
        {% else %}
        {# 비활성화 시켜주는 class, 회색처리되서 클릭되지 않게함 #}
        <li>
            <a class="btn" href="{{ request.path }}?page={{ forloop.counter }}">{{ forloop.counter }}</a>
        </li>
        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <!-- 이전페이지 객체가 있으면 [Next]버튼 활성화 -->
        <a class="btn" href="/stack/?page={{ page_obj.next_page_number }}"><i class="fa-solid fa-angle-right"></i></a>
        {% else %}
        <li class="page-item disabled"> <!-- 여기 비활성화 안해주면 이상한데로 계속 감-->
            <a class="btn disabled"><i class="fa-solid fa-angle-right"></i></a>
        </li>
        {% endif %}
    </ul>
    {% endif %}


    <footer>
        <p>
            Copyright © 2023. Kokonenne All Rights Reserved.
        </p>
    </footer>

    <script src="{%static 'js/index.js'%}"></script>
</body>

</html>

ofcourse/stack/templates/stack/stack_search.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ofcourse</title>
    <!-- fontawesome css cdn-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
        integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- normalize css cdn-->
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <!-- global css -->
    <link rel="stylesheet" href="{%static 'css/style.css'%}">
</head>

<body class="list-page">
    <header>
        {% include 'partials/navbar.html' %}
    </header>

    <div class="title-area">
        <h2 class="page-title">스택별 기업</h2>
        <h3>세상의 거진 모든 스택을 모았다!👀</h3>
    </div>

    <div class="search-area">
        <!-- 검색 폼 -->
        <form action="{% url 'stack:search' %}" method="GET">
            {% csrf_token %}
            <!-- 검색 -->
            <div class="search-bar">
                <input type="text" name="search" id="search-bar" placeholder="스택명을 입력해주세요 !">
                <button type="submit" class="search-btn">검색</button>
            </div>
        </form>
    </div>

    {% if search %}
    <div class="content">
        <h3 class="search-result-area">검색하신 <span class="text-highlight">{{search}}</span>에 대한 정보입니다.</h3>
        <main class="list-area skill">
            <ul>
                <!-- search 정보 -->
                {% for c in stack %}
                <li class="list-card">
                    <div class="company-icon">
                        <a href="/stack/{{c.id}}">
                            <img src="{{ c.logo }}" alt="스택 로고">
                        </a>
                    </div>
                    <div class="info-box">
                        <a href="/stack/{{c.id}}" style="text-decoration: none;">
                            <h3>{{ c.name }}</h3>
                        </a>
                    </div>
                    <p class="skill-info">
                        유사 기술 스택 목록 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ c.assort }}
                    </p>
                    <div class="skill-list">
                        <ul>
                            {% for rs in c.related_stack_set.iterator %}
                            <li><a class="skill-icon" href="/stack/{{rs.related_stack_pk}}"><img
                                        src="{{ rs.related_stack_logo }}" alt="아이콘"></a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </li>
                {% endfor %}
            </ul>
            {% else %}
        </main>
        {% endif %}
    </div>


    <footer>
        <p>
            Copyright © 2023. Kokonenne All Rights Reserved.
        </p>
    </footer>
</body>

</html>