ofcourse/course/urls.py
from course import views
from django.urls import path

app_name = 'course'
urlpatterns = [
    # '/course/'
    # path('', views.Courselist.as_view(), name='course'),
]

ofcourse/ofcourse/urls.py
from django.contrib import admin
from django.urls import path, include
from course import views
from course.views import index


urlpatterns = [
    path('', index, name='index'),

    path('admin/', admin.site.urls),

    # path('list/', list),
    path('course/', views.course, name='course'),

    # company
    path('company/', include('company.urls')),

    # stack
    path('stack/', include('stack.urls')),

    # search 
    path('search/', views.search, name='search'),

    # filter 
    path('filter/', views.filter, name='filter'),
]

ofcourse/stack/urls.py
from stack import views
from django.urls import path

app_name = 'stack'

urlpatterns = [
    # '/stack/
    path('', views.StackList.as_view(), name="stack"),

    # stack_detail
    path('<int:pk>/',views.StackDetail.as_view(), name='stack_detail'),

    # stack_search
    path('search/', views.search, name='search'),
]

ofcourse/course/models.py
from django.db import models

# Create your models here.

# 강의 모델
class Course(models.Model):
    url = models.TextField(default=None)
    img_url = models.TextField( default=None)
    title = models.CharField(max_length=200,default=None)
    teacher = models.CharField(max_length=200,default='')
    headline = models.TextField(default='')
    level = models.CharField(max_length=30,default='')
    score = models.FloatField(default=0, null=True)
    course_time = models.CharField(max_length=100,default='')
    student_cnt = models.IntegerField(default=0, null=True)
    recommend = models.IntegerField(default=0,null=True)
    review_cnt = models.IntegerField(default=0,null=True)
    price = models.IntegerField(default='',null=True)
    rank = models.FloatField(default=None, null=True)
    stack = models.ManyToManyField("Stack",through='Course_Stack')
    sentiment = models.FloatField(default=0, null=True)

    class Meta:
        db_table='Course'

# 스택테이블
class Stack(models.Model):  
    name = models.CharField(max_length=50,unique=True)
    logo = models.TextField(default='')
    assort = models.CharField(max_length=50,default='')
    described = models.TextField()

    class Meta:
        db_table ='Stack'

# Course_Stack 중간테이블
class Course_Stack(models.Model):
    course =models.ForeignKey('Course',on_delete=models.CASCADE)
    stack =models.ForeignKey('Stack',on_delete=models.CASCADE)

    class Meta:
        db_table='Course_Stack'

# 회사테이블
class Company(models.Model):
    name = models.CharField(max_length=50,unique=True)
    logo = models.TextField(default='')
    stack_info = models.CharField(max_length=200,default='')
    stack = models.ManyToManyField("Stack",through='Company_Stack')
    category = models.CharField(max_length=50,null=True)
    company_link = models.TextField(default='')
    company_recruit_link = models.TextField(default='')

    class Meta:
        db_table = 'Company'

#Company_Stack 중간테이블
class Company_Stack(models.Model):
    company =models.ForeignKey('Company',on_delete=models.CASCADE)
    stack =models.ForeignKey('Stack',on_delete=models.CASCADE)

    class Meta:
        db_table = 'Company_Stack'


#related_stack 테이블
class Related_Stack(models.Model):
    stack_name= models.ForeignKey('Stack',on_delete=models.CASCADE)
    related_stack = models.CharField(max_length=50)
    related_stack_logo = models.TextField(default='')
    related_stack_pk = models.IntegerField(default=0)

    class Meta:
        db_table = 'Related_Stack'

#stack_dict 테이블 입니다.
class Stack_Dict(models.Model):
    stack_name= models.ForeignKey('Stack',on_delete=models.CASCADE)
    search_word= models.CharField(max_length=20)

    class Meta:
        db_table = 'Stack_Dict'

ofcourse/course/forms.py
from django import forms

class CourseSearchForm(forms.Form):
    search_course = forms.CharField(label='Search Course')

ofcourse/course/views.py
from django.shortcuts import render
from .models import Course, Stack, Course_Stack
from django.views.generic import ListView, FormView,View
from .forms import CourseSearchForm
from django.db.models import Q
from django.core.paginator import Paginator

# Create your views here.
def index(request):
    stack_list = Stack.objects.all()
    return render(request, 'index.html', {'stack_list': stack_list})

def course(request):
    course_list = Course.objects.all()
    stack = Stack.objects.all()
    context = {
        'course_list':course_list,
        'stack':stack
    }
    
    sort = request.GET.get('sort','') #url의 쿼리스트링을 가져온다. 없는 경우 공백을 리턴한다

    if sort == 'review':
        context['course_list'] = Course.objects.all().order_by('-review_cnt')
    elif sort == 'recommend':
        context['course_list'] = Course.objects.all().order_by('-recommend')
    elif sort == 'score':
        context['course_list'] = Course.objects.all().order_by('-score')
    elif sort == 'free':
        context['course_list'] = Course.objects.filter(price__iexact = 0)
    else:
        context['course_list'] = Course.objects.all().order_by('rank')

    paginator = Paginator(context['course_list'], 96)
    page = request.GET.get('page', '')
    course = paginator.get_page(page)
    context['course_list'] = course
        
    return render(request, 'course/list.html', context)


# search FBV형
def search(request):
    course_list = Course.objects.all().order_by('rank')
    search = request.GET.get('search','')
    if search:
        search_list = course_list.filter(
            Q(title__icontains=search) |
            Q(teacher__icontains=search) |
            Q(headline__icontains=search) |
            Q(stack__name__icontains=search) |
            Q(stack__stack_dict__search_word__icontains=search)
        ).distinct()
        # print(search_list.query)

        # print(search_list[5].title)
    paginator = Paginator(search_list, 12)
    page = request.GET.get('page', '')
    course = paginator.get_page(page)

    return render(request, 'course/course_search.html',{'course':course, 'search':search})

    # search FBV형2
def filter(request):
    course_list = Course.objects.all().order_by('rank')
    stack_list = Stack.objects.all()
    s = request.GET.getlist('s')
    filter_list = None
    stack = None
    if s: # 체크박스에서 값이 넘어오면
        course_query = Q()
        stack_query = Q()
        for i in s:
            # or 조건을 주기 위함
            course_query = course_query | Q(stack__name__iexact=i)
            stack_query = stack_query | Q(name__iexact=i)
        filter_list = course_list.filter(course_query)
        stack = stack_list.filter(stack_query)
    
    context = {
        'course':filter_list, 
        'stack':stack,
        'stack_list':stack_list
    }
    
    return render(request, 'course/course_filter.html', context)

ofcourse/stack/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from course.models import Stack, Related_Stack, Company, Course_Stack
from django.shortcuts import get_object_or_404
from django.db.models import Q

# Create your views here.
class StackList(ListView): 
    model = Stack
    template_name = "stack/stack_list.html"
    ordering = '?'
    paginate_by = 12

    def get_context_data(self, **kwargs):
        context = super(StackList, self).get_context_data()
        context['stack'] = Stack.objects.all()

        filter = self.request.GET.get('filter','') #url의 쿼리스트링을 가져온다. 없는 경우 공백을 리턴한다

        if filter == 'frontend':
            context['object_list'] = Stack.objects.filter(assort__iexact = '프론트엔드')
            context['page'] = 'filter'
        elif filter == 'backend':
            context['object_list'] = Stack.objects.filter(assort__iexact = '백엔드')
            context['page'] = 'filter'
        elif filter == 'database':
            context['object_list'] = Stack.objects.filter(assort__iexact = '데이터베이스')
            context['page'] = 'filter'
        elif filter == 'DevOps':
            context['object_list'] = Stack.objects.filter(assort__iexact = '데브옵스')
            context['page'] = 'filter'
        elif filter == 'Language':
            context['object_list'] = Stack.objects.filter(assort__iexact = '언어')
            context['page'] = 'filter'
        elif filter == 'data':
            context['object_list'] = Stack.objects.filter(assort__iexact = '데이터')
            context['page'] = 'filter'
        elif filter == 'TestingTool':
            context['object_list'] = Stack.objects.filter(assort__iexact = '테스팅툴')
            context['page'] = 'filter'
        elif filter == 'businessTool':
            context['object_list'] = Stack.objects.filter(assort__iexact = '협업툴')
            context['page'] = 'filter'
        elif filter == 'mobile':
            context['object_list'] = Stack.objects.filter(assort__iexact = '모바일')
            context['page'] = 'filter'

        return context


class StackDetail(DetailView):
    model = Stack
    template_name = 'stack/stack_detail.html'

    def get_context_data(self, **kwargs):
        context = super(StackDetail, self).get_context_data()
        try:
            context['course'] = Course_Stack.objects.filter(stack_id=self.object.id).order_by('course__rank')[:5]
        except Exception as e:
            context['course'] = None

        return context

def search(request):
    stacks = Stack.objects.all()
    search = request.GET.get('search','')
    if search:
        stack_list = stacks.filter(
            Q(name__icontains=search) |
            Q(stack_dict__search_word__iexact=search)
        ).distinct()
        return render(request, 'stack/stack_search.html', {'stack':stack_list, 'search':search})
    else:
        return render(request,  'stack/stack_search.html')

    # def get_context_data(self, **kwargs):
    #     context = super(StackDetail, self).get_context_data()
    #     st =Stack.objects.filter(id=2).prefetch_related('company_set')[0]
    #     print(st)
    #     context['companies'] = st.course_set.all()
    #     print(context['companies'])
    #     for i in context['companies']:
    #         print("cours :", i)

        # context = super(StackDetail, self).get_context_data()
        # st =Stack.objects.filter(id=2).prefetch_related('course_set')[0]
        # print(st)
        # context['courses'] = st.course_set.all()
        # print(context['courses'])
        # for i in context['courses']:
        #     print("cours :", i)
        
        # context['companies'] = Stack.objects.filter(id=1).prefetch_related('company_set')
        # return context

    # def get_context_data(self, **kwargs):
    #     context = super(StackDetail, self).get_context_data()
    #     context['test'] = Company.objects.all()
    #     return context

ofcourse/course/templates/course/course_filter.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ofcourse</title>
    <!-- fontawesome css cdn-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
        integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- normalize css cdn-->
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <!-- global css -->
    <link rel="stylesheet" href="{%static 'css/style.css'%}">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="{%static 'js/index.js'%}"></script>
    <script type="text/javascript" src="{%static 'js/ready.js' %}"></script>
</head>

<body class="list-page">
    <header>
        {% include 'partials/navbar.html' %}
    </header>
    <!-- <h1>Course Search</h1> -->
    <div class="title-area">
        <h2 class="page-title">검색 결과</h2>
    </div>
    <!-- 검색 폼 -->
    <!-- 검색 -->
    <div class="search-area">
        <form action="{% url 'search' %}" method="GET">
            {% csrf_token %}
            <div class="search-bar">
                <input type="text" name="search" id="search-bar">
                <button type="submit" class="search-btn">검색</button>
            </div>
        </form>
    </div>

    <div class="content">
        <div class="filter-area">
            <div class="btn-wrap">
                <div class="btn-l-wrap">
                    <button class="btn" onclick="filterSelection('언어')" id="start"> 언어</button>
                    <button class="btn" onclick="filterSelection('프론트엔드')"> 프론트엔드</button>
                    <button class="btn" onclick="filterSelection('백엔드')"> 백엔드</button>
                    <button class="btn" onclick="filterSelection('데이터베이스')"> 데이터베이스</button>
                    <button class="btn" onclick="filterSelection('데브옵스')"> 데브옵스</button>
                    <button class="btn" onclick="filterSelection('데이터')"> 데이터</button>
                    <button class="btn" onclick="filterSelection('모바일')"> 모바일</button>
                    <button class="btn" onclick="filterSelection('테스팅툴')"> 테스팅툴</button>
                    <button class="btn" onclick="filterSelection('협업툴')"> 협업툴</button>
                </div>
            </div>
            <form action="{% url 'filter' %}" method="get">
                <div class="skill-info-area">
                    <div class="container">
                        {% for s in stack_list %}
                        {% if s.course_stack_set.exists %}
                        <span class="filterDiv {{s.assort}}">
                            <i class="skill-logo" style="background-image: url('{{ s.logo }}');">
                            </i>
                            <input type="checkbox" class="btn-check" onclick="ready()" id="btncheck{{forloop.counter}}" autocomplete="off"
                                name="s" , value="{{s.name}}">
                            <label class="btn btn-outline-primary" for="btncheck{{forloop.counter}}">{{s.name}}</label>
                        </span>
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
                <button type="submit" class="search-btn">검색</button>
            </form>
        </div>
        <main class="list-area">
            <h3 class="search-result-area">검색하신 {% for s in stack %} <span class="text-highlight"
                    style="margin-right: .8rem;"># {{s.name}} </span> {% endfor %} 강의 정보입니다.</h3>
            <ul>
                {% for c in course %}
                <li class="list-card">
                    <a href="{{c.url}}" target="_blank">
                        <div class="img-box">
                            <img src="{{ c.img_url }}" alt="강의 예시 이미지">
                        </div>
                    </a>
                    <div class="info-box">
                        <h3>
                            <a href="{{c.url}}" target="_blank">{{c.title|truncatechars:50 }}</a>
                        </h3>
                        <div class="keywords">
                            {% for s in c.stack.iterator %}
                            <span class="point">{{s.name}}</span>
                            {% endfor %} 
                        </div>
                        <p class="level">레벨 - {{ c.level }}</p>
                        <p class="teacher">{{ c.teacher }}</p>
                        <p class="rate">{{ c.score }}</p>
                        {% if c.price == null %}
                        <a href="{{c.url}}" style="text-decoration: none;"  target="_blank">
                            <p class="price">🔗</p>
                        </a>
                        {% elif c.price == 0 %}
                        <p class="price">무료</p>
                        {% else %}
                        <p class="price">{{ c.price|intcomma }}</p>
                        {% endif %}
                    </div>
                </li>
                {% endfor %}
            </ul>
        </main>
    </div>
    <footer>
        <p>
            Copyright © 2023. Kokonenne All Rights Reserved.
        </p>
    </footer>
</body>

<script>
    document.addEventListener("DOMContentLoaded", () => {
        document.getElementById("start").click();
    });
</script>
<script type="text/javascript" src="{%static 'js/list.js' %}"></script>

</html>

ofcourse/course/templates/course/course_search.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ofcourse</title>
    <!-- fontawesome css cdn-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
        integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- normalize css cdn-->
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <!-- global css -->
    <link rel="stylesheet" href="{%static 'css/style.css'%}">
    <script src="{%static 'js/index.js'%}"></script>
</head>

<body class="list-page">
    <header>
        {% include 'partials/navbar.html' %}
    </header>
    <!-- <h1>Course Search</h1> -->
    <div class="title-area">
        <h2 class="page-title">강의 찾기</h2>
    </div>
    <!-- 검색 폼 -->
    <!-- 검색 -->
    <div class="search-area">
        <form action="{% url 'search' %}" method="GET">
            {% csrf_token %}
            <div class="search-bar">
                <input type="text" name="search" id="search-bar">
                <button type="submit" class="search-btn">검색</button>
            </div>
        </form>
    </div>
    <!-- search 정보 -->
    {% if search %}
    <div class="content">
        <h3 class="search-result-area">검색하신 <span class="text-highlight">{{search}}</span> 강의 정보입니다.</h3>
        <main class="list-area">
            <ul>
                {% for c in course %}
                <li class="list-card">
                    <a href="{{c.url}}" target="_blank">
                        <div class="img-box">
                            <img src="{{ c.img_url }}" alt="강의 예시 이미지">
                        </div>
                    </a>
                    <div class="info-box">
                        <h3>
                            <a href="{{c.url}}" target="_blank">{{c.title|truncatechars:50 }}</a>
                        </h3>
                        <div class="keywords">
                            {% for s in c.stack.iterator %}
                            <span class="point">{{s.name}}</span>
                            {% endfor %}
                        </div>
                        <p class="level">레벨 - {{ c.level }}</p>
                        <p class="teacher">{{ c.teacher }}</p>
                        <p class="rate">{{ c.score }}</p>
                        {% if c.price == null %}
                        <p class="price">🔗</p>
                        {% elif c.price == 0 %}
                        <p class="price">무료</p>
                        {% else %}
                        <p class="price">{{ c.price|intcomma }}</p>
                        {% endif %}
                    </div>
                </li>
                {% endfor %}
                {% else %}
                <h1>찾고 있는 강의를 검색창에 입력해주세요.</h1>
                {% endif %}
            </ul>

            <div class="pagination">
                {% if course.has_previous %}
                <a href="?page=1&search={{search}}" class="btn"><i class="fa-solid fa-angle-left"></i>First</a>
                <a href="?page={{course.previous_page_number}}&search={{search}}" class="btn"><i
                        class="fa-solid fa-angles-left"></i>Previous</a>
                {% endif %}

                <span>{{course.number}} / {{course.paginator.num_pages}}</span>

                {% if course.has_next %}
                <a href="?page={{course.next_page_number}}&search={{search}}" class="btn"><i
                        class="fa-solid fa-angle-right"></i>Next</a>
                <a href="?page={{course.paginator.num_pages}}&search={{search}}" class="btn"><i
                        class="fa-solid fa-angles-right"></i>Last</a>
                {% endif %}
            </div>
        </main>
    </div>
    <footer>
        <p>
            Copyright © 2023. Kokonenne All Rights Reserved.
        </p>
    </footer>
</body>

</html>

ofcourse/course/templates/course/list.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ofcourse</title>
    <!-- fontawesome css cdn-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
        integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- normalize css cdn-->
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <!-- global css -->
    <link rel="stylesheet" href="{%static 'css/style.css'%}">

    <!-- <link rel="stylesheet" href="{%static 'css/filter.css'%}"> -->
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"> -->
    
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script type="text/javascript" src="{%static 'js/list.js' %}"></script>
    <script type="text/javascript" src="{%static 'js/disabledbtn.js' %}"></script>
    <script type="text/javascript" src="{%static 'js/ready.js' %}"></script>
</head>

<body class="list-page">
    <header>
        {% include 'partials/navbar.html' %}
    </header>

    <div class="title-area">
        <h2 class="page-title">강의 찾기</h2>
        <h3>공부하고 싶은 기술스택의 강의를 찾아보세요🔎</h3>
    </div>

    <div class="search-area">

        <form action="{% url 'search' %}" method="GET">
            {% csrf_token %}
            <div class="search-bar">
                <input type="text" name="search" id="search-bar">
                <button type="submit" class="search-btn">검색</button>
            </div>
        </form>
    </div>

    <div class="content">
        <div class="filter-area">
            <div class="btn-wrap">
                <div class="btn-l-wrap">
                    <button class="btn" onclick="filterSelection('언어')" id="start"> 언어</button>
                    <button class="btn" onclick="filterSelection('프론트엔드')"> 프론트엔드</button>
                    <button class="btn" onclick="filterSelection('백엔드')"> 백엔드</button>
                    <button class="btn" onclick="filterSelection('데이터베이스')"> 데이터베이스</button>
                    <button class="btn" onclick="filterSelection('데브옵스')"> 데브옵스</button>
                    <button class="btn" onclick="filterSelection('데이터')"> 데이터</button>
                    <button class="btn" onclick="filterSelection('모바일')"> 모바일</button>
                    <button class="btn" onclick="filterSelection('테스팅툴')"> 테스팅툴</button>
                    <button class="btn" onclick="filterSelection('협업툴')"> 협업툴</button>
                </div>
                <div class="btn-r-wrap">
                    <p class="title">필터 </p>
                    <a class="btn" href="/course">기본</a>
                    <a class="btn" href="?sort=review">리뷰많은순</a>
                    <a class="btn" href="?sort=recommend">추천많은순</a>
                    <a class="btn" href="?sort=score">평점순</a>
                    <a class="btn" href="?sort=free">무료</a>
                </div>
            </div>

            <form action="{% url 'filter' %}" method="get">
                <div class="skill-info-area">
                    <div class="container">
                        {% for s in stack %}
                        {% if s.course_stack_set.exists %}
                        <span class="filterDiv {{s.assort}}">
                            <i class="skill-logo" style="background-image: url('{{ s.logo }}');">
                            </i>
                            <input type="checkbox" class="btn-check" onclick="ready()" id="btncheck{{forloop.counter}}" autocomplete="off"
                                name="s" , value="{{s.name}}">
                            <label class="btn btn-outline-primary" for="btncheck{{forloop.counter}}">{{s.name}}</label>
                        </span>
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
                <button type="submit" onclick="disbtn()" class="search-btn">검색</button>
            </form>
        </div>
        <main class="list-area">
            <ul>
                {% for c in course_list %}
                <li class="list-card">
                    <a href="{{c.url}}" target="_blank">
                        <div class="img-box">
                            <img src="{{ c.img_url }}" alt="강의 예시 이미지">
                        </div>
                    </a>
                    <div class="info-box">
                        <h3>
                            <a href="{{c.url}}" target="_blank">{{c.title|truncatechars:50 }}</a>
                        </h3>
                        <div class="keywords">
                            {% for s in c.stack.iterator %}
                            <span class="point">{{s.name}}</span>
                            {% endfor %} 
                        </div>
                        <p class="level">레벨 - {{ c.level }}</p>
                        <p class="teacher">{{ c.teacher }}</p>
                        <p class="rate">{{ c.score }}(리뷰긍정도 : {{c.sentiment}})</p>
                        {% if c.price == null %}
                        <a href="{{c.url}}" style="text-decoration: none;"  target="_blank">
                            <p class="price">🔗</p>
                        </a>
                        {% elif c.price == 0 %}
                        <p class="price">무료</p>
                        {% else %}
                        <p class="price">{{ c.price|intcomma}}</p>
                        {% endif %}
                    </div>
                </li>
                {% endfor %}

            </ul>
        </main>
    </div>
    <!-- Pagination-->
    <ul class="pagination">

        <!-- 이전 페이지 객체가 있으면 '이전' 버튼 활성화 -->
        {% if course_list.has_previous %}
        <a class="btn" href="/course/?page={{ page_obj.previous_page_number }}" tabindex="-1"><i
                class="fa-solid fa-angle-left"></i></a>
        {% else %}
        <!-- <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">이전</a>
            </li> -->
        <a class="btn disabled" tabindex="-1"><i class="fa-solid fa-angle-left"></i></a>
        {% endif %}


        {# 페이지를 번호로 출력하기 #}
        {% for page in course_list.paginator.page_range %} {# 전체 페이지수를 가져옴 #}
        {# 현재 선택한 페이지 번호는 비활성화 시킴 #}
        {% if course_list.number == forloop.counter %}
        {# 위에 page_obj 대신 page 로도 되는지 테스트해보기 #}
        <li>
            {# 현재 선택한 페이지 번호는 활성화 시킴 #}
            <a class="btn on" href="{{ request.path }}?page={{ forloop.counter }}">{{ forloop.counter }}</a>
        </li>
        {% else %}
        {# 비활성화 시켜주는 class, 회색처리되서 클릭되지 않게함 #}
        <li>
            <a class="btn" href="{{ request.path }}?page={{ forloop.counter }}">{{ forloop.counter }}</a>
        </li>
        {% endif %}
        {% endfor %}

        {% if course_list.has_next %}
        <!-- 이전페이지 객체가 있으면 [Next]버튼 활성화 -->
        <a class="btn" href="/course/?page={{ course_list.next_page_number }}"><i class="fa-solid fa-angle-right"></i></a>
        {% else %}
        <li class="page-item disabled"> <!-- 여기 비활성화 안해주면 이상한데로 계속 감-->
            <a class="btn disabled"><i class="fa-solid fa-angle-right"></i></a>
        </li>
        {% endif %}
    </ul>
    <footer>
        <p>
            Copyright © 2023. Kokonenne All Rights Reserved.
        </p>
    </footer>
</body>

<script>
    document.addEventListener("DOMContentLoaded", () => {
        document.getElementById("start").click();
    });
</script>

<script src="{%static 'js/index.js'%}"></script>
</html>