ofcourse/company/urls.py
from company import views
from django.urls import path

app_name = 'company'

urlpatterns = [

    # '/company/
    path('', views.CompanyList.as_view(), name='company'),

    # company_detail
    path('<int:pk>/',views.Companydetail.as_view(), name='company_detail'),
    
    # company_search
    path('search/', views.search, name='search'),
 
    # company_filter
    path('filter/', views.filter, name='filter'),
]

ofcourse/ofcourse/urls.py
from django.contrib import admin
from django.urls import path, include
from course import views
from course.views import index


urlpatterns = [
    path('', index, name='index'),

    path('admin/', admin.site.urls),

    # path('list/', list),
    path('course/', views.course, name='course'),

    # company
    path('company/', include('company.urls')),

    # stack
    path('stack/', include('stack.urls')),

    # search 
    path('search/', views.search, name='search'),

    # filter 
    path('filter/', views.filter, name='filter'),
]

ofcourse/stack/urls.py
from stack import views
from django.urls import path

app_name = 'stack'

urlpatterns = [
    # '/stack/
    path('', views.StackList.as_view(), name="stack"),

    # stack_detail
    path('<int:pk>/',views.StackDetail.as_view(), name='stack_detail'),

    # stack_search
    path('search/', views.search, name='search'),
]

ofcourse/company/models.py
from django.db import models
from django.shortcuts import render

# Create your models here.

ofcourse/company/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from course.models import Company, Course_Stack, Stack
from django.db.models import Q
from django.core.paginator import Paginator


# Create your views here.
class CompanyList(ListView):
    model = Company
    template_name = 'company/company_list.html'

    ordering = 'pk'

    paginate_by = 15

    def get_context_data(self, **kwargs):
        context = super(CompanyList, self).get_context_data()
        context['stack'] = Stack.objects.all()

        filter = self.request.GET.get('filter','') #url의 쿼리스트링을 가져온다. 없는 경우 공백을 리턴한다

        if filter == 'foreign':
            context['object_list'] = Company.objects.filter(stack_info__iexact = '외국기업')
            context['page'] = 'filter'
        elif filter == 'comprehensive':
            context['object_list'] = Company.objects.filter(category__iexact = '종합 기업')
            context['page'] = 'filter'
        elif filter == 'social':
            context['object_list'] = Company.objects.filter(category__iexact = '소셜/컨텐츠 기업')
            context['page'] = 'filter'
        elif filter == 'ecommerce':
            context['object_list'] = Company.objects.filter(category__iexact = '이커머스 기업')
            context['page'] = 'filter'
        elif filter == 'trip':
            context['object_list'] = Company.objects.filter(category__iexact = '여행 기업')
            context['page'] = 'filter'
        elif filter == 'finance':
            context['object_list'] = Company.objects.filter(category__iexact = '금융/보험 기업')
            context['page'] = 'filter'
        elif filter == 'education':
            context['object_list'] = Company.objects.filter(category__iexact = '교육 기업')
            context['page'] = 'filter'
        elif filter == 'mobility':
            context['object_list'] = Company.objects.filter(category__iexact = '모빌리티 기업')
            context['page'] = 'filter'
        elif filter == 'foodtech':
            context['object_list'] = Company.objects.filter(category__iexact = '푸드테크 기업')
            context['page'] = 'filter'
        elif filter == 'realestate':
            context['object_list'] = Company.objects.filter(category__iexact = '부동산/인테리어 기업')
            context['page'] = 'filter'
        elif filter == 'healthcare':
            context['object_list'] = Company.objects.filter(category__iexact = '헬스케어 기업')
            context['page'] = 'filter'
        elif filter == 'ai':
            context['object_list'] = Company.objects.filter(category__iexact = '인공지능 기업')
            context['page'] = 'filter'
        elif filter == 'recruitment':
            context['object_list'] = Company.objects.filter(category__iexact = '직장 기업')
            context['page'] = 'filter'
        elif filter == 'etc':
            context['object_list'] = Company.objects.filter(category__iexact = '기타 기업')
            context['page'] = 'filter'

        return context


class Companydetail(DetailView):
    model = Company
    template_name = 'company/company_detail.html'

    def get_context_data(self, **kwargs):
        context = super(Companydetail, self).get_context_data()
        # context['company_detail'] = Company.objects.all()
        # context['id_values'] = Company.objects.filter(id=1)    

        return context




# 검색 함수
def search(request):
    company = Company.objects.all()
    search = request.GET.get('search','')

    if search:
        company_list = company.filter(
            Q(name__icontains=search) | # 회사 이름 검색
            Q(stack__name__iexact=search) |  # 스택 이름 검색
            Q(stack__stack_dict__search_word__iexact=search)  # 스택 사전에 있는 네임으로 검색   
        ).distinct()
        return render(request, 'company/company_search.html', {'company':company_list, 'search':search})

    else:
        return render(request,  'company/company_search.html')




def filter(request):
    company_list = Company.objects.all()

    s = request.GET.getlist('s')
    ss = Q()

    if s:
        company_query = Q()
        for i in s:
            compnay_company_queryquery = company_query | Q(category__iexact=i)
        # com = company_list.filter(company_query)



    return render(request, 'company/filter.html',{'company_list' : company_list})

ofcourse/company/templates/company/company_list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ofcourse</title>
    <!-- fontawesome css cdn-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
        integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- normalize css cdn-->
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <!-- global css -->
    <link rel="stylesheet" href="{%static 'css/style.css'%}">
</head>

<body class="list-page">
    <header>
        {% include 'partials/navbar.html' %}
    </header>
    <div class="title-area">
        <h2 class="page-title">기업별 기술 스택</h2>
        <h3>기업들이 무슨 기술 스택을 사용하는지 확인해봐~ 🤣</h3>
    </div>
    <div class="search-area">
        <form action="{% url 'company:search' %}" method="GET">
            {% csrf_token %}
            <div class="search-bar">
                <input type="text" name="search" id="search-bar" placeholder="회사명을 입력해주세요!">
                <button type="submit" class="search-btn">검색</button>
            </div>
        </form>
    </div>


    <!-- 검색을 했을 때 -->
    <div class="content">
        <div class="filter-area">
            <div class="btn-wrap">
                <div class="btn-r-wrap">
                    <p class="title">필터 </p>
                    <a class="btn" href="/company">All</a>
                    <a class="btn" href="?filter=foreign">외국기업</a>
                    <a class="btn" href="?filter=comprehensive">종합</a>
                    <a class="btn" href="?filter=social">소셜/컨텐츠</a>
                    <a class="btn" href="?filter=ecommerce">이커머스</a>
                    <a class="btn" href="?filter=trip">여행</a>
                    <a class="btn" href="?filter=finance">금융/보험</a>
                    <a class="btn" href="?filter=education">교육</a>
                    <a class="btn" href="?filter=mobility">모빌리티</a>
                    <a class="btn" href="?filter=foodtech">푸드테크</a>
                    <a class="btn" href="?filter=realestate">부동산/인테리어</a>
                    <a class="btn" href="?filter=healthcare">헬스케어</a>
                    <a class="btn" href="?filter=ai">인공지능</a>
                    <a class="btn" href="?filter=recruitment">채용</a>
                    <a class="btn" href="?filter=etc">기타</a>
                </div>
            </div>
        </div>
        <main class="list-area skill">
            <ul>
                {% for c in object_list %}
                <li class="list-card">
                    <div class="company-icon">
                        <a href="{{c.id}}">
                            <img src="{{ c.logo }}" alt="강의 예시 이미지">
                        </a>
                    </div>
                    <div class="info-box">
                        <a href="{{c.id}}" style="text-decoration: none;">
                            <h3>{{ c.name }} {% if c.category %}<span class="sort">{{ c.category }}</span>{% endif %}</h3>
                        </a>
                    </div>
                    <p class="skill-info">
                        {{ c.stack_info}}
                    </p>
                    <div class="skill-list">
                        <ul>
                            {% for stack in c.stack.iterator %}
                            <li><a class="skill-icon" href="/stack/{{stack.id}}"><img src="{{ stack.logo }}"
                                        alt="아이콘"></a></li>
                            {% endfor %}
                            <li><a class="see-more" href="{{c.id}}">자세히보기</a></li>
                        </ul>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </main>
    </div>
    {% if page != 'filter' %}
    <ul class="pagination">

        <!-- 이전 페이지 객체가 있으면 '이전' 버튼 활성화 -->
        {% if page_obj.has_previous %}
        <a class="btn" href="/company/?page={{ page_obj.previous_page_number }}" tabindex="-1"><i
                class="fa-solid fa-angle-left"></i></a>
        {% else %}
        <!-- <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">이전</a>
            </li> -->
        <a class="btn disabled" tabindex="-1"><i class="fa-solid fa-angle-left"></i></a>
        {% endif %}


        {# 페이지를 번호로 출력하기 #}
        {% for page in page_obj.paginator.page_range %} {# 전체 페이지수를 가져옴 #}
        {# 현재 선택한 페이지 번호는 비활성화 시킴 #}
        {% if page_obj.number == forloop.counter %}
        {# 위에 page_obj 대신 page 로도 되는지 테스트해보기 #}
        <li>
            {# 현재 선택한 페이지 번호는 활성화 시킴 #}
            <a class="btn on" href="{{ request.path }}?page={{ forloop.counter }}">{{ forloop.counter }}</a>
        </li>
        {% else %}
        {# 비활성화 시켜주는 class, 회색처리되서 클릭되지 않게함 #}
        <li>
            <a class="btn" href="{{ request.path }}?page={{ forloop.counter }}">{{ forloop.counter }}</a>
        </li>
        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <!-- 이전페이지 객체가 있으면 [Next]버튼 활성화 -->
        <a class="btn" href="/company/?page={{ page_obj.next_page_number }}"><i class="fa-solid fa-angle-right"></i></a>
        {% else %}
        <li class="page-item disabled"> <!-- 여기 비활성화 안해주면 이상한데로 계속 감-->
            <a class="btn disabled"><i class="fa-solid fa-angle-right"></i></a>
        </li>
        {% endif %}

    </ul>
    {% endif %}
    <footer>
        <p>
            Copyright © 2023. Kokonenne All Rights Reserved.
        </p>
    </footer>
    <script src="{%static 'js/index.js'%}"></script>
</body>

</html>

ofcourse/company/templates/company/company_search.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ofcourse</title>
    <!-- fontawesome css cdn-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
        integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- normalize css cdn-->
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <!-- global css -->
    <link rel="stylesheet" href="{%static 'css/style.css'%}">
</head>

<body class="list-page">
    <header>
        {% include 'partials/navbar.html' %}
    </header>
    <div class="title-area">
        <h2 class="page-title">기업별 스택</h2>
        <h3>기업들이 무슨 기술 스택을 사용하는지 확인해봐~🤣</h3>
    </div>
    <div class="search-area">
        <!-- 검색 폼 -->
        <form action="{% url 'company:search' %}" method="GET">
            {% csrf_token %}
            <!-- 검색 -->
            <div class="search-bar">
                <input type="text" name="search" id="search-bar" placeholder="회사명을 입력해주세요 !">
                <button type="submit" class="search-btn">검색</button>
            </div>
        </form>
    </div>

    {% if search %}
    <!-- <h1>검색하신 <span class="point">{{ search }}</span> 관련 정보입니다.</h1> -->
    <div class="content">
        <h3 class="search-result-area">검색하신 <span class="text-highlight">{{search}}</span>에 대한 정보입니다.</h3>
        <main class="list-area skill">
            <ul>
                <!-- search 정보 -->
                {% for c in company %}
                <li class="list-card">
                    <div class="company-icon">
                        <a href="/company/{{c.id}}">
                            <img src="{{ c.logo }}" alt="기업 로고">
                        </a>
                    </div>
                    <div class="info-box">
                        <a href="/company/{{c.id}}" style="text-decoration: none;">
                            <h3>{{ c.name }}</h3>
                        </a>
                    </div>
                    <p class="skill-info">
                        {{ c.stack_info }}
                        {% if c.category %}
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ c.category }}
                        {% endif %}
                    </p>
                    <div class="skill-list">
                        <ul>
                            {% for stack in c.stack.iterator %}
                            <li><a class="skill-icon" href="/stack/{{stack.id}}"><img src="{{ stack.logo }}"
                                        alt="아이콘"></a></li>
                            {% endfor %}
                            <li><a class="see-more" href="{{c.id}}">더보기</a></li>
                        </ul>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </main>
        {% endif %}
    </div>


    <footer>
        <p>
            Copyright © 2023. Kokonenne All Rights Reserved.
        </p>
    </footer>
    <script src="{%static 'js/index.js'%}"></script>
</body>

</html>

ofcourse/company/templates/company/filter.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ofcourse</title>
    <!-- fontawesome css cdn-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
        integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- normalize css cdn-->
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <!-- global css -->
    <link rel="stylesheet" href="{%static 'css/style.css'%}">
    <script src="{%static 'js/index.js'%}"></script>
</head>

<body class="list-page">
    <header>
        {% include 'partials/navbar.html' %}
    </header>
    <!-- <h1>Course Search</h1> -->
    <div class="title-area">
        <h2 class="page-title">검색 결과</h2>
    </div>
    <!-- 검색 폼 -->
    <!-- 검색 -->
    <div class="search-area">
        <form action="{% url 'company:search' %}" method="GET">
            {% csrf_token %}
            <div class="search-bar">
                <input type="text" name="search" id="search-bar">
                <button type="submit" class="search-btn">검색</button>
            </div>
        </form>
    </div>

    <div class="content">
        <div class="filter-area">
            <div class="btn-wrap">
                <button class="btn" onclick="filterSelection('국내기업')" id="start"> 국내기업</button>
                <button class="btn" onclick="filterSelection('외국기업')"> 외국기업</button>
            </div>
            <form action="{% url 'company:filter' %}" method="get">
                <div class="skill-info-area">
                    <div class="container">
                        {% for s in company_list %}
                        {% if s %}
                        <span class="filterDiv {{s.stack_info}}">
                            <i class="skill-logo" style="background-image: url('{{ s.logo }}');">
                            </i>
                            <input type="checkbox" class="btn-check" id="btncheck{{forloop.counter}}" autocomplete="off"
                            name="s" , value="{{s.name}}">
                            <label class="btn btn-outline-primary" for="btncheck{{forloop.counter}}">{{s.name}}</label>
                        </span>                        
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
                <button type="submit" class="search-btn">검색</button>
            </form>
        </div>
        <main class="list-area">
            <h3 class="search-result-area">검색하신 {% for s in company %} <span class="text-highlight"
                    style="margin-right: .8rem;"># {{s.name}} </span> {% endfor %} 기업 정보입니다.</h3>
        </main>
    </div>
    <footer>
        <p>
            Copyright © 2023. Kokonenne All Rights Reserved.
        </p>
    </footer>
</body>

<script>
    document.addEventListener("DOMContentLoaded", () => {
        document.getElementById("start").click();
    });
</script>
<script type="text/javascript" src="{%static 'js/list.js' %}"></script>

</html>

ofcourse/company/templates/company/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ofcourse</title>
    <!-- fontawesome css cdn-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
        integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- normalize css cdn-->
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <!-- global css -->
    <link rel="stylesheet" href="{%static 'css/style.css'%}">
</head>

<body class="list-page">
    <header>
        {% include 'partials/navbar.html' %}
    </header>
    <div class="title-area">
        <h2 class="page-title">기업별 스택</h2>
        <h3>기업들이 무슨 기술 스택을 사용하는지 확인해봐~🤣</h3>
    </div>
    <div class="search-area">
        <form action="{% url 'company:search' %}" method="GET">
            {% csrf_token %}
            <div class="search-bar">
                <input type="text" name="search" id="search-bar" placeholder="회사명을 입력해주세요!">
                <button type="submit" class="search-btn">검색</button>
            </div>
        </form>
    </div>


    <!-- 검색을 했을 때 -->
    <div class="content">
        <main class="list-area skill">
            <ul>
                {% for c in company_list %}
                <li class="list-card">
                    <div class="company-icon">
                        <a href="{{c.id}}">
                            <img src="{{ c.logo }}" alt="강의 예시 이미지">
                        </a>
                    </div>
                    <div class="info-box">
                        <a href="{{c.id}}" style="text-decoration: none;">
                            <h3>{{ c.name }}</h3>
                        </a>
                    </div>
                    <p class="skill-info">
                        {{ c.stack_info }}
                        {% if c.category %}
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ c.category }}
                        {% endif %}

                    </p>
                    <div class="skill-list">
                        <ul>
                            {% for stack in c.stack.iterator %}
                            <li><a class="skill-icon" href="/stack/{{stack.id}}"><img src="{{ stack.logo }}"
                                        alt="아이콘"></a></li>
                            {% endfor %}
                            <li><a class="see-more" href="{{c.id}}">자세히보기</a></li>
                        </ul>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </main>
    </div>

    <ul class="pagination">

        <!-- 이전 페이지 객체가 있으면 '이전' 버튼 활성화 -->
        {% if page_obj.has_previous %}
        <a class="btn" href="/company/?page={{ page_obj.previous_page_number }}" tabindex="-1"><i
                class="fa-solid fa-angle-left"></i></a>
        {% else %}
        <!-- <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">이전</a>
            </li> -->
        <a class="btn disabled" tabindex="-1"><i class="fa-solid fa-angle-left"></i></a>
        {% endif %}


        {# 페이지를 번호로 출력하기 #}
        {% for page in page_obj.paginator.page_range %} {# 전체 페이지수를 가져옴 #}
        {# 현재 선택한 페이지 번호는 비활성화 시킴 #}
        {% if page_obj.number == forloop.counter %}
        {# 위에 page_obj 대신 page 로도 되는지 테스트해보기 #}
        <li>
            {# 현재 선택한 페이지 번호는 활성화 시킴 #}
            <a class="btn on" href="{{ request.path }}?page={{ forloop.counter }}">{{ forloop.counter }}</a>
        </li>
        {% else %}
        {# 비활성화 시켜주는 class, 회색처리되서 클릭되지 않게함 #}
        <li>
            <a class="btn" href="{{ request.path }}?page={{ forloop.counter }}">{{ forloop.counter }}</a>
        </li>
        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <!-- 이전페이지 객체가 있으면 [Next]버튼 활성화 -->
        <a class="btn" href="/company/?page={{ page_obj.next_page_number }}"><i class="fa-solid fa-angle-right"></i></a>
        {% else %}
        <li class="page-item disabled">
            <!-- 여기 비활성화 안해주면 이상한데로 계속 감-->
            <a class="btn disabled"><i class="fa-solid fa-angle-right"></i></a>
        </li>
        {% endif %}

    </ul>

    <footer>
        <p>
            Copyright © 2023. Kokonenne All Rights Reserved.
        </p>
    </footer>
    <script src="{%static 'js/index.js'%}"></script>
</body>

</html>

ofcourse/company/templates/company/search.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ofcourse</title>
    <!-- fontawesome css cdn-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
        integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- normalize css cdn-->
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <!-- global css -->
    <link rel="stylesheet" href="{%static 'css/style.css'%}">
</head>

<body class="list-page">
    <header>
        {% include 'partials/navbar.html' %}
    </header>
    <div class="title-area">
        <h2 class="page-title">기업별 스택</h2>
        <h3>기업들이 무슨 기술 스택을 사용하는지 확인해봐~🤣</h3>
    </div>
    <div class="search-area">
        <!-- 검색 폼 -->
        <form action="{% url 'company:search' %}" method="GET">
            {% csrf_token %}
            <!-- 검색 -->
            <div class="search-bar">
                <input type="text" name="search" id="search-bar" placeholder="회사명을 입력해주세요 !">
                <button type="submit" class="search-btn">검색</button>
            </div>
        </form>
    </div>

    {% if search %}
    <!-- <h1>검색하신 <span class="point">{{ search }}</span> 관련 정보입니다.</h1> -->
    <div class="content">
        <h3 class="search-result-area">검색하신 <span class="text-highlight">{{search}}</span>에 대한 정보입니다.</h3>
        <main class="list-area skill">
            <ul>
                <!-- search 정보 -->
                {% for c in company %}
                <li class="list-card">
                    <div class="company-icon">
                        <a href="/company/{{c.id}}">
                            <img src="{{ c.logo }}" alt="기업 로고">
                        </a>
                    </div>
                    <div class="info-box">
                        <a href="/company/{{c.id}}" style="text-decoration: none;">
                            <h3>{{ c.name }}</h3>
                        </a>
                    </div>
                    <p class="skill-info">
                        {{ c.stack_info }}
                    </p>
                    <div class="skill-list">
                        <ul>
                            {% for stack in c.stack.iterator %}
                            <li><a class="skill-icon" href="/stack/{{stack.id}}"><img src="{{ stack.logo }}"
                                        alt="아이콘"></a></li>
                            {% endfor %}
                            <li><a class="see-more" href="{{c.id}}">더보기</a></li>
                        </ul>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </main>
        {% endif %}
    </div>


    <footer>
        <p>
            Copyright © 2023. Kokonenne All Rights Reserved.
        </p>
    </footer>
    <script src="{%static 'js/index.js'%}"></script>
</body>

</html>